Repository s4u/pgp-keys-map, pull requests merged in 2022-11, with the labels that each got.

#1130 Add new key for org.apache.xbean
  resources/pgp-keys-map.list
Labels: enhancement

#1131 Add new key for org.graalvm
  resources/pgp-keys-map.list
Labels: enhancement

#1132 Add new key for com.github.javaparser
  resources/pgp-keys-map.list
Labels: enhancement

#1133 Add new key for org.codehaus.plexus
  resources/pgp-keys-map.list
Labels: enhancement

#1134 Split org.codehaus groupId to separate projects
  resources/pgp-keys-map.list
Labels: enhancement

#1135 Add new key for com.github.luben
  resources/pgp-keys-map.list
Labels: enhancement

#1136 Allow not found key for org.codehaus.plexus:plexus-archiver:4.5.0
  resources/pgp-keys-map.list
Labels: enhancement

#1137 Add new key for org.apache.maven
  resources/pgp-keys-map.list
Labels: enhancement

#1138 Revert "Allow not found key for org.codehaus.plexus:plexus-archiver:4.5.0"
  resources/pgp-keys-map.list
Labels: invalid

#1139 Merge keys for org.eclipse.jetty and subgroups
  resources/pgp-keys-map.list
Labels: enhancement

#1140 Add new key for com.google.protobuf:protobuf-java
  resources/pgp-keys-map.list
Labels: enhancement

#1141 Add new key for org.tmatesoft
  resources/pgp-keys-map.list
Labels: enhancement

#1150 new key for commons-compress
  pgp-keys-map-test1/pom.xml
  resources/pgp-keys-map.list
Labels: enhancement

#1152 Bump pgpverify-maven-plugin from 1.15.0 to 1.16.0
  pom.xml
Labels: dependencies
